/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyAddressRouteImport } from './routes/verify-address'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LocationRouteImport } from './routes/location'
import { Route as CreateRequestRouteImport } from './routes/create-request'
import { Route as CreateOfferRouteImport } from './routes/create-offer'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyAddressSubmittedRouteImport } from './routes/verify-address.submitted'
import { Route as RequestIdRouteImport } from './routes/request.$id'
import { Route as NeighborIdRouteImport } from './routes/neighbor.$id'
import { Route as LocationScanningRouteImport } from './routes/location.scanning'
import { Route as LocationClusterRouteImport } from './routes/location.cluster'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'

const VerifyAddressRoute = VerifyAddressRouteImport.update({
  id: '/verify-address',
  path: '/verify-address',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRequestRoute = CreateRequestRouteImport.update({
  id: '/create-request',
  path: '/create-request',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOfferRoute = CreateOfferRouteImport.update({
  id: '/create-offer',
  path: '/create-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyAddressSubmittedRoute = VerifyAddressSubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => VerifyAddressRoute,
} as any)
const RequestIdRoute = RequestIdRouteImport.update({
  id: '/request/$id',
  path: '/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborIdRoute = NeighborIdRouteImport.update({
  id: '/neighbor/$id',
  path: '/neighbor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationScanningRoute = LocationScanningRouteImport.update({
  id: '/scanning',
  path: '/scanning',
  getParentRoute: () => LocationRoute,
} as any)
const LocationClusterRoute = LocationClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => LocationRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/create-offer': typeof CreateOfferRoute
  '/create-request': typeof CreateRequestRoute
  '/location': typeof LocationRouteWithChildren
  '/messages': typeof MessagesRoute
  '/patterns': typeof PatternsRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/success': typeof SuccessRoute
  '/verify-address': typeof VerifyAddressRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/location/cluster': typeof LocationClusterRoute
  '/location/scanning': typeof LocationScanningRoute
  '/neighbor/$id': typeof NeighborIdRoute
  '/request/$id': typeof RequestIdRoute
  '/verify-address/submitted': typeof VerifyAddressSubmittedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/create-offer': typeof CreateOfferRoute
  '/create-request': typeof CreateRequestRoute
  '/location': typeof LocationRouteWithChildren
  '/messages': typeof MessagesRoute
  '/patterns': typeof PatternsRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/success': typeof SuccessRoute
  '/verify-address': typeof VerifyAddressRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/location/cluster': typeof LocationClusterRoute
  '/location/scanning': typeof LocationScanningRoute
  '/neighbor/$id': typeof NeighborIdRoute
  '/request/$id': typeof RequestIdRoute
  '/verify-address/submitted': typeof VerifyAddressSubmittedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/create-offer': typeof CreateOfferRoute
  '/create-request': typeof CreateRequestRoute
  '/location': typeof LocationRouteWithChildren
  '/messages': typeof MessagesRoute
  '/patterns': typeof PatternsRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/success': typeof SuccessRoute
  '/verify-address': typeof VerifyAddressRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/location/cluster': typeof LocationClusterRoute
  '/location/scanning': typeof LocationScanningRoute
  '/neighbor/$id': typeof NeighborIdRoute
  '/request/$id': typeof RequestIdRoute
  '/verify-address/submitted': typeof VerifyAddressSubmittedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/create-offer'
    | '/create-request'
    | '/location'
    | '/messages'
    | '/patterns'
    | '/profile'
    | '/profile-setup'
    | '/success'
    | '/verify-address'
    | '/home'
    | '/chat/$id'
    | '/location/cluster'
    | '/location/scanning'
    | '/neighbor/$id'
    | '/request/$id'
    | '/verify-address/submitted'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/create-offer'
    | '/create-request'
    | '/location'
    | '/messages'
    | '/patterns'
    | '/profile'
    | '/profile-setup'
    | '/success'
    | '/verify-address'
    | '/home'
    | '/chat/$id'
    | '/location/cluster'
    | '/location/scanning'
    | '/neighbor/$id'
    | '/request/$id'
    | '/verify-address/submitted'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/create-offer'
    | '/create-request'
    | '/location'
    | '/messages'
    | '/patterns'
    | '/profile'
    | '/profile-setup'
    | '/success'
    | '/verify-address'
    | '/_authenticated/home'
    | '/chat/$id'
    | '/location/cluster'
    | '/location/scanning'
    | '/neighbor/$id'
    | '/request/$id'
    | '/verify-address/submitted'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CreateOfferRoute: typeof CreateOfferRoute
  CreateRequestRoute: typeof CreateRequestRoute
  LocationRoute: typeof LocationRouteWithChildren
  MessagesRoute: typeof MessagesRoute
  PatternsRoute: typeof PatternsRoute
  ProfileRoute: typeof ProfileRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  SuccessRoute: typeof SuccessRoute
  VerifyAddressRoute: typeof VerifyAddressRouteWithChildren
  ChatIdRoute: typeof ChatIdRoute
  NeighborIdRoute: typeof NeighborIdRoute
  RequestIdRoute: typeof RequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-address': {
      id: '/verify-address'
      path: '/verify-address'
      fullPath: '/verify-address'
      preLoaderRoute: typeof VerifyAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-request': {
      id: '/create-request'
      path: '/create-request'
      fullPath: '/create-request'
      preLoaderRoute: typeof CreateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-offer': {
      id: '/create-offer'
      path: '/create-offer'
      fullPath: '/create-offer'
      preLoaderRoute: typeof CreateOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-address/submitted': {
      id: '/verify-address/submitted'
      path: '/submitted'
      fullPath: '/verify-address/submitted'
      preLoaderRoute: typeof VerifyAddressSubmittedRouteImport
      parentRoute: typeof VerifyAddressRoute
    }
    '/request/$id': {
      id: '/request/$id'
      path: '/request/$id'
      fullPath: '/request/$id'
      preLoaderRoute: typeof RequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighbor/$id': {
      id: '/neighbor/$id'
      path: '/neighbor/$id'
      fullPath: '/neighbor/$id'
      preLoaderRoute: typeof NeighborIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/scanning': {
      id: '/location/scanning'
      path: '/scanning'
      fullPath: '/location/scanning'
      preLoaderRoute: typeof LocationScanningRouteImport
      parentRoute: typeof LocationRoute
    }
    '/location/cluster': {
      id: '/location/cluster'
      path: '/cluster'
      fullPath: '/location/cluster'
      preLoaderRoute: typeof LocationClusterRouteImport
      parentRoute: typeof LocationRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LocationRouteChildren {
  LocationClusterRoute: typeof LocationClusterRoute
  LocationScanningRoute: typeof LocationScanningRoute
}

const LocationRouteChildren: LocationRouteChildren = {
  LocationClusterRoute: LocationClusterRoute,
  LocationScanningRoute: LocationScanningRoute,
}

const LocationRouteWithChildren = LocationRoute._addFileChildren(
  LocationRouteChildren,
)

interface VerifyAddressRouteChildren {
  VerifyAddressSubmittedRoute: typeof VerifyAddressSubmittedRoute
}

const VerifyAddressRouteChildren: VerifyAddressRouteChildren = {
  VerifyAddressSubmittedRoute: VerifyAddressSubmittedRoute,
}

const VerifyAddressRouteWithChildren = VerifyAddressRoute._addFileChildren(
  VerifyAddressRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CreateOfferRoute: CreateOfferRoute,
  CreateRequestRoute: CreateRequestRoute,
  LocationRoute: LocationRouteWithChildren,
  MessagesRoute: MessagesRoute,
  PatternsRoute: PatternsRoute,
  ProfileRoute: ProfileRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  SuccessRoute: SuccessRoute,
  VerifyAddressRoute: VerifyAddressRouteWithChildren,
  ChatIdRoute: ChatIdRoute,
  NeighborIdRoute: NeighborIdRoute,
  RequestIdRoute: RequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
